name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node: [ lts/* ]
    steps:
      - name: Checkout zendit-node
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm run build

      - name: Run tests
        run: npm run test
        env:
          ZENDIT_API_KEY: ${{ secrets.ZENDIT_API_KEY }}